### ISSUE TITLE
libnlopt.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TFLQW** [robotlearn/pyrobolearn#19]
Hi! when i was preparing the env for the package, i have follow the instruction in the readme text, Everything is ok no error! But when i ran the pyrobolearn/examples/kinematics/forward it pull the error like that!

Some ROS packages were not found... Skipping prl.simulators.middlewares.ROS...
pybullet build time: Nov 17 2019 13:30:40
current_dir=/home/tiboy/py3.5/lib/python3.5/site-packages/pybullet_envs/bullet
Dart could not be found on this system... Skipping prl.simulators.Dart...
MuJoCo could not be found on this system... Skipping prl.simulators.Mujoco...
Raisim could not be found on this system... Skipping prl.simulators.Raisim...
RBDL could not be found on this system... Skipping priorities.RBDLModelInterface...
Traceback (most recent call last):
  File "/home/tiboy/simulation/pyrobolearn/pyrobolearn/optimizers/nlopt_optimizer.py", line 15, in <module>
    import nlopt
  File "/home/tiboy/py3.5/lib/python3.5/site-packages/nlopt.py", line 35, in <module>
    _nlopt = swig_import_helper()
  File "/home/tiboy/py3.5/lib/python3.5/site-packages/nlopt.py", line 31, in swig_import_helper
    _mod = imp.load_module('_nlopt', fp, pathname, description)
  File "/home/tiboy/py3.5/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/tiboy/py3.5/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libnlopt.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tiboy/simulation/pyrobolearn/examples/kinematics/inverse/ik.py", line 14, in <module>
    from pyrobolearn.simulators import Bullet
  File "/home/tiboy/simulation/pyrobolearn/pyrobolearn/__init__.py", line 98, in <module>
    from . import priorities
  File "/home/tiboy/simulation/pyrobolearn/pyrobolearn/priorities/__init__.py", line 13, in <module>
    from . import solvers
  File "/home/tiboy/simulation/pyrobolearn/pyrobolearn/priorities/solvers/__init__.py", line 10, in <module>
    from .nlp_task_solver import NLPTaskSolver
  File "/home/tiboy/simulation/pyrobolearn/pyrobolearn/priorities/solvers/nlp_task_solver.py", line 15, in <module>
    from pyrobolearn.optimizers.nlopt_optimizer import NLopt
  File "/home/tiboy/simulation/pyrobolearn/pyrobolearn/optimizers/nlopt_optimizer.py", line 17, in <module>
    raise ImportError(e.__str__() + "\n HINT: you can install nlopt via `pip install nlopt`.")
ImportError: libnlopt.so.0: cannot open shared object file: No such file or directory
 HINT: you can install nlopt via `pip install nlopt`. 

But i have pip the nlopt its version is 2.4.2.post2. So can you help me fix these problem

**Comment by TFLQW** [comment]
ok! I have find the solution because of the Dynamic Link Library problem!
execulate this command: sudo ln -s /the path to libnlopt.so.0/libnlopt.so.0 /usr/lib
That's ok~~
