### ISSUE TITLE
Recent versions of Torch (>1.1.0) produces errors in GP model training

### ISSUE THREAD

**Issue by lrozo** [robotlearn/pyrobolearn#23]
Our requirements file indicates that the torch library can be any >=1.1.0, however, it seems there were some relevant changes in recent versions (>1.1.0) that produces the following error when using GPR models (for example, when running gpr.py in the examples folder)

`Traceback (most recent call last):
  File "/home/rol2rng/Code/IIT/pyrobolearn_fork/examples/models/gpr.py", line 41, in <module>
    f = model.sample(x, num_samples=10, to_numpy=True)`

  `File "/home/rol2rng/Code/IIT/pyrobolearn_fork/pyrobolearn/models/gp/gp.py", line 665, in sample
return self._convert_to_numpy(f.sample(num_samples))`

  `File "/home/rol2rng/Code/IIT/pyrobolearn_official/venv35/lib/python3.5/site-packages/gpytorch/distributions/multivariate_normal.py", line 167, in sample
    return self.rsample(sample_shape=sample_shape, base_samples=base_samples)`

  `File "/home/rol2rng/Code/IIT/pyrobolearn_official/venv35/lib/python3.5/site-packages/gpytorch/distributions/multivariate_normal.py", line 136, in rsample
    res = covar.zero_mean_mvn_samples(num_samples) + self.loc.unsqueeze(0)`

  `File "/home/rol2rng/Code/IIT/pyrobolearn_official/venv35/lib/python3.5/site-packages/gpytorch/lazy/lazy_tensor.py", line 1112, in zero_mean_mvn_samples
    covar_root = self.root_decomposition()`

  `File "/home/rol2rng/Code/IIT/pyrobolearn_official/venv35/lib/python3.5/site-packages/gpytorch/lazy/lazy_tensor.py", line 901, in root_decomposition
    )(*self.representation())`

  `File "/home/rol2rng/Code/IIT/pyrobolearn_official/venv35/lib/python3.5/site-packages/gpytorch/functions/_root_decomposition.py", line 64, in forward
    eigenvalues, eigenvectors = lanczos_tridiag_to_diag(t_mat)`

  `File "/home/rol2rng/Code/IIT/pyrobolearn_official/venv35/lib/python3.5/site-packages/gpytorch/utils/lanczos.py", line 166, in lanczos_tridiag_to_diag
    return batch_symeig(t_mat)`

  `File "/home/rol2rng/Code/IIT/pyrobolearn_official/venv35/lib/python3.5/site-packages/gpytorch/utils/eig.py", line 28, in batch_symeig
    eigenvalues[i] = evals.masked_fill_(1 - mask, 1)`

 ` File "/home/rol2rng/Code/IIT/pyrobolearn_official/venv35/lib/python3.5/site-packages/torch/tensor.py", line 362, in __rsub__
    return _C._VariableFunctions.rsub(self, other)`

`RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.`

This does not happen when **installing specifically torch 1.1.0**. However, note that the **latest torch version requires Python >=3.6**. 

So, short-term solution: Fix the torch version in requirements to be == 1.1.0. Long-term solution, identify the required change in the sampling function of GP according to the latest Torch version.

**Comment by lrozo** [comment]
@bdelhaisse have you had a look at this issue with the recent version of Pytorch (and python 3.6)? It'd be nice to make GPR-based code compatible with the latest versions.
